### ISSUE TITLE
Issue with running 'Dummy Request 1' sample. Error 500 and response saved with .json extension not .pdf extension

### ISSUE THREAD

**Issue by aitest321** [sivcan/ResponseToFile-Postman#10]
hello, I am using latest Postman v9.0.5 and Node.js 14.17.0 (x64) and npm.
The 'Dummy Request 1' sample from https://documenter.getpostman.com/view/3407886/RWgp1fB5 is failing with Error 500 and the response file created is named 'Dummy Request 1.json' not 'Dummy Request 1.pdf'

Below is my Postman response for POST http://localhost:3000/write
Can anyone help? Thx!

{id: "2fb539f9-87f7-48fb-94fa-47a217368b00", status: "Internal Server Error", code: 500…}
id: "2fb539f9-87f7-48fb-94fa-47a217368b00"
status: "Internal Server Error"
code: 500
header: [8]
stream: {…}
type: "Buffer"
data: [1396]
cookie: [0]
responseTime: 5
responseSize: 1396

And below is error from node script.js console
 
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (fs.js:1487:5)
    at C:\aintest321\PostmanResponseToFile\master\script.js:30:13
    at Layer.handle [as handle_request] (C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\layer.js:95:5)
    at C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\aintest321\PostmanResponseToFile\master\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\aintest321\PostmanResponseToFile\master\node_modules\body-parser\lib\types\urlencoded.js:100:7)

**Comment by aitest321** [comment]
Hmm, I see kaisajanzen having same error in https://github.com/sivcan/ResponseToFile-Postman/issues/6#issuecomment-913874140 , so I am not the only one with issue.
